### ISSUE TITLE
GitHub Actions configuration file contains syntax error (oops)

### ISSUE THREAD

**Issue by eecavanna** [microbiomedata/nmdc-field-notes#11]
Offending line (the final one in this excerpt):

```yaml
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: [ node-version: ${ { matrix.node-version } }, cache: "npm" ]
```

Will change to:

```yaml
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with: { node-version: "${{ matrix.node-version }}", cache: "npm" }
```

Here's the diff of that:

```diff
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
-         with: [ node-version: ${ { matrix.node-version } }, cache: "npm" ]
+         with: { node-version: "${{ matrix.node-version }}", cache: "npm" }
```
